package sim.gui.control;
/**
 * 
 * Dtails....
 * 
 * 
 * <p>
 * The naming convention
 *  <li>I...... : Interface class</li>
 *  <li>A...... : Abstract class</li>
 *  <li>C...... : Concrete class</li>
 *  
 *  <li>doSomething  : Do it method </li>
 *  <li>runSomething : Run it method </li>
 *  <li>getSomething : Getter </li>
 *  <li>setSomething : Set attribute</li>
 *
 *  <li>i...... : Instance variable </li>
 *  <li>l...... : Local variable </li>
 *  <li>s...... : Static variable </li>
 *  <li>a...... : Argument </li>
 *  <li>n...... : ENUM </li>
 *
 *  <li>VARIABLE_NAME : Constant variable </li>
 * </ul>
 * </p>
 * 
 * 
 * @date : Mar 21, 2019
 * @author : S. J. Yun - cp5113@naver.com, +82-10-9254-5153
 *
 * @version : 
 * Mar 21, 2019 : Coded by S. J. Yun.
 *
 *
 */

import java.io.File;
import java.util.Calendar;
import java.util.Iterator;
import java.util.List;

import elements.facility.CAirport;
import elements.facility.CTaxiwayLink;
import elements.facility.CTaxiwayNode;
import elements.mobile.vehicle.CAircraft;
import elements.util.geo.CCoordination;
import javafx.application.Platform;
import javafx.event.Event;
import javafx.event.EventHandler;
import javafx.fxml.FXML;
import javafx.scene.CacheHint;
import javafx.scene.canvas.Canvas;
import javafx.scene.canvas.GraphicsContext;
import javafx.scene.control.MenuItem;
import javafx.scene.input.MouseButton;
import javafx.scene.input.MouseEvent;
import javafx.scene.input.ScrollEvent;
import javafx.scene.layout.BorderPane;
import javafx.scene.layout.Pane;
import javafx.scene.paint.Color;
import sim.CAtsolSimMain;
import sim.clock.CDispatchAircraftThreadByTime;
import sim.gui.CDrawingInform;
import sim.gui.IDrawingObject;
import sim.gui.view.CAtsolSimGuiView;

public class CAtsolSimGuiControl {
	/*
	================================================================
	
			           Initializing Section
	
	================================================================
	*/
	
	@SuppressWarnings("unused")
	private static CAtsolSimGuiView fGuiview;
	@FXML
	private MenuItem MenuRunProject;
	@FXML
	private MenuItem MenuLoadProject;
	@FXML
	private MenuItem MenuSaveProject;
	@FXML
	private MenuItem MenuClose;
	
	@FXML
	private Pane	SimCanvasPane;
	@FXML
	private Canvas   SimCanvas;
	@FXML
	private BorderPane RootBoderPane;
	private static CAtsolSimGuiControl iInstance;
	/*
	================================================================
	
						Methods Section
	
	================================================================
	 */
	public void MenuCloseAction() {
		System.exit(0);
	}
	
	public void MenuRunProjectAction() {		
		
		
		if(!CAtsolSimMain.getInstance().getSimClock().isRunning()) {
			System.out.println("Reload Project Files");
			CAtsolSimMain.getInstance().connectTable();
			CAtsolSimMain.getInstance().loadEnvironment(new File(CAtsolSimMain.getInstance().getProjectFileName()));		
			CAtsolSimMain.getInstance().createDrawingObjectList();
			
			
			System.out.println("Create link between Time and Elements(Controller only. The other element will be generated by Dispatch)");
			CAtsolSimMain.getInstance().getSimClock().createLinkBetweenTimeAndElements();
			
			System.out.println("Generate Thread Dispatch");
			CDispatchAircraftThreadByTime.getInstance().initializeDispatch();
			
			System.out.println("Clock Setting...");			
			CAtsolSimMain.getInstance().getSimClock().setStartTimeInMilliSeconds(CDispatchAircraftThreadByTime.getInstance().getSimStartTime()          );
			CAtsolSimMain.getInstance().getSimClock().setEndTimeInMilliSeconds(  CDispatchAircraftThreadByTime.getInstance().getSimStartTime() + 36000000);			
			Thread myThread = new Thread(CAtsolSimMain.getInstance().getSimClock(),"SimClockThread");
			
			System.out.println("Clock is Start");
			myThread.start();

			System.out.println("Create Thread and Start Thread (eg., Aircraft, Controller...)");
			CAtsolSimMain.getInstance().getSimClock().createThreadOfElements();
			
			
			
		}else {
			CAtsolSimMain.getInstance().getSimClock().stopClock();			
		}
			
	}
	
	public synchronized void drawDrawingObjectList()  {	
		Platform.runLater(()->{
			// Cleaning Canvas
			GraphicsContext gc = SimCanvas.getGraphicsContext2D();
			gc.setFill(Color.LIGHTGRAY);
			gc.fillRect(0, 0, SimCanvas.getWidth(), SimCanvas.getHeight());
			
			
			Iterator<IDrawingObject> iter = CAtsolSimMain.getInstance().getDrawingObjectList().iterator();
			while(iter.hasNext()) {
				IDrawingObject lAnObject = iter.next();
				CDrawingInform lDrawingInform = lAnObject.getDrawingInform();
				if(!lDrawingInform.isVisible()) continue; 
				
				// Drawing			
				switch(lDrawingInform.getShape()) {
				case LINE:
					List<CCoordination> lCoordList = lDrawingInform.getCoordinationList();
					for(int loopList = 0; loopList < lCoordList.size()-1; loopList++) {
						double p1X = lCoordList.get(loopList).getXCoordination();
						double p1Y = lCoordList.get(loopList).getYCoordination();
						double p2X = lCoordList.get(loopList+1).getXCoordination();
						double p2Y = lCoordList.get(loopList+1).getYCoordination();
						
						CCoordination p1 = changeCoordinatesInCanvas(p1X, p1Y);
						CCoordination p2 = changeCoordinatesInCanvas(p2X, p2Y);
						
						gc.setStroke(lDrawingInform.getColor());
						gc.beginPath();
						gc.moveTo(p1.getXCoordination(), p1.getYCoordination());
						gc.lineTo(p2.getXCoordination(), p2.getYCoordination());
						gc.closePath();
						gc.stroke();					
					}
					break;
				case DOT:
					CCoordination lCoordination = lDrawingInform.getCoordinationList().get(0);
					double p1X = lCoordination.getXCoordination();
					double p1Y = lCoordination.getYCoordination();
					CCoordination p1 = changeCoordinatesInCanvas(p1X, p1Y);
					if(p1.getXCoordination()<0 || p1.getXCoordination()>SimCanvas.getWidth() || p1.getYCoordination()<0 || p1.getYCoordination()>SimCanvas.getHeight() ) {
						continue;
					}
					
					gc.setFill(lDrawingInform.getColor());			
					double lRadius =  50*CAtsolSimMain.getInstance().getViewPointR();
					gc.fillOval(p1.getXCoordination()-lRadius/2, p1.getYCoordination()-lRadius/2,lRadius, lRadius);
					
					break;
				case CIRCLE:
					CCoordination lCoordinationCircle = lDrawingInform.getCoordinationList().get(0);
					double p1XCircle = lCoordinationCircle.getXCoordination();
					double p1YCircle = lCoordinationCircle.getYCoordination();
					CCoordination p1Circle = changeCoordinatesInCanvas(p1XCircle, p1YCircle);
					if(p1Circle.getXCoordination()<0 || p1Circle.getXCoordination()>SimCanvas.getWidth() || p1Circle.getYCoordination()<0 || p1Circle.getYCoordination()>SimCanvas.getHeight() ) {
						continue;
					}					
					double lRadiusCircle =  10*CAtsolSimMain.getInstance().getViewPointR();
					gc.setStroke(lDrawingInform.getColor());
					gc.strokeOval(p1Circle.getXCoordination()-lRadiusCircle/2, p1Circle.getYCoordination()-lRadiusCircle/2,lRadiusCircle, lRadiusCircle);
					
					break;
				case RECTANGEL:
					break;
				case SQUARE:
					break;
				default:
					break;
				} //switch(lDrawingInform.getShape()) {
				
			}//while(iter.hasNext()) {
			
			
			try {
				Thread.sleep(1);
			} catch (InterruptedException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		});
		
		
		
//		System.out.println(CAtsolSimMain.getInstance().getiViewPoint());
//		System.out.println(CAtsolSimMain.getInstance().getiViewPointR());
		
	}
	
	private CCoordination changeCoordinatesInCanvas(double aXCoord, double aYCoord) {
		// Initialize
		CCoordination outputCoordination = new CCoordination(aXCoord, aYCoord);
		Double lCanvasheight = SimCanvas.getHeight();
		Double lCanvaswidth  = SimCanvas.getWidth();
		
		// get View Points
		double lCenterX = CAtsolSimMain.getInstance().getViewPoint().getXCoordination();
		double lCenterY = CAtsolSimMain.getInstance().getViewPoint().getYCoordination();
		double lRatio   = CAtsolSimMain.getInstance().getViewPointR();
		
		
		// Normalize Coordination
		Double newXCoord = (aXCoord * lRatio - lCenterX * lRatio + lCanvaswidth/2);
		Double newYCoord = (lCenterY * lRatio - aYCoord * lRatio + lCanvasheight/2); 
		outputCoordination.setXCoordination(newXCoord);
		outputCoordination.setYCoordination(newYCoord);
		
		return outputCoordination;		
	}
	private CCoordination changeCoordinatesFromCanvas(double aXCoord, double aYCoord) {
		CCoordination outputCoordination = new CCoordination(aXCoord, aYCoord);
		Double lCanvasheight = SimCanvas.getHeight();
		Double lCanvaswidth  = SimCanvas.getWidth();
		// get View Points
		double lCenterX = CAtsolSimMain.getInstance().getViewPoint().getXCoordination();
		double lCenterY = CAtsolSimMain.getInstance().getViewPoint().getYCoordination();
		double lRatio   = CAtsolSimMain.getInstance().getViewPointR();
		
		// Normalize Coordination
		Double newXCoord = (aXCoord + lCenterX * lRatio - lCanvaswidth/2)/lRatio;
		Double newYCoord = (lCenterY * lRatio  + lCanvasheight/2 - aYCoord)/lRatio; 
		outputCoordination.setXCoordination(newXCoord);
		outputCoordination.setYCoordination(newYCoord);
		
		return outputCoordination;
	}
	
	public void initialize() {
						
		SimCanvas.widthProperty().bind(SimCanvasPane.widthProperty());
		SimCanvas.heightProperty().bind(SimCanvasPane.heightProperty());
		SimCanvas.widthProperty().addListener(evt -> drawDrawingObjectList());
		SimCanvas.heightProperty().addListener(evt -> drawDrawingObjectList());
		SimCanvas.setCache(true);
		SimCanvas.setCacheHint(CacheHint.SPEED);
		CCanvasEventHandler lCanvasEventHandler = new CCanvasEventHandler();
		SimCanvas.setOnKeyPressed(lCanvasEventHandler);
		SimCanvas.setOnMouseMoved(lCanvasEventHandler);
		SimCanvas.setOnMouseClicked(lCanvasEventHandler);
		SimCanvas.setOnMousePressed(lCanvasEventHandler);
		SimCanvas.setOnMouseDragged(lCanvasEventHandler);
		SimCanvas.setOnMouseDragEntered(lCanvasEventHandler);
		SimCanvas.setOnScroll(lCanvasEventHandler);
		
		
	}
	
	
	
	private class CCanvasEventHandler implements EventHandler<Event>{
		double iMousePositionXPrev = 0;
		double iMousePositionYPrev = 0;
		double iMousePositionXCurrent= 0;
		double iMousePositionYCurrent = 0;
		
		double iScrollStep			   =0.1;
		int	   iScrollCount			   =0;
		@Override
		public void handle(Event aEvent) {
			// TODO Auto-generated method stub
//			System.out.println(aEvent.getEventType());
//			System.out.println("Input!!");
			switch(aEvent.getEventType().toString()) {
			case "MOUSE_DRAGGED":							
				// Wheel Dragging
				if(((MouseEvent) aEvent).getButton() == MouseButton.MIDDLE){
					iMousePositionXCurrent = ((MouseEvent) aEvent).getSceneX();
					iMousePositionYCurrent = ((MouseEvent) aEvent).getSceneY();
					double lMovementX = (iMousePositionXCurrent-iMousePositionXPrev);
					double lMovementY = (iMousePositionYCurrent-iMousePositionYPrev);
					CAtsolSimMain.getInstance().getViewPoint().moveX(-lMovementX/CAtsolSimMain.getInstance().getViewPointR());
					CAtsolSimMain.getInstance().getViewPoint().moveY(lMovementY/CAtsolSimMain.getInstance().getViewPointR());					
					drawDrawingObjectList();
					iMousePositionXPrev = iMousePositionXCurrent;
					iMousePositionYPrev = iMousePositionYCurrent;
				}
				break;
			case "MOUSE_MOVED":
				drawDrawingObjectList();
				Platform.runLater(()->{
					
					iMousePositionXCurrent = ((MouseEvent) aEvent).getX();
					iMousePositionYCurrent = ((MouseEvent) aEvent).getY();
					//				System.out.println(iMousePositionXCurrent);
					CCoordination lOriginalCoordination =  changeCoordinatesFromCanvas(iMousePositionXCurrent, iMousePositionYCurrent);

					double lDistance = Double.MAX_VALUE;
					IDrawingObject lTheObject = null;
					Iterator<IDrawingObject> iter = CAtsolSimMain.getInstance().getDrawingObjectList().iterator();
					while(iter.hasNext()) {
						IDrawingObject lAnObject = iter.next();
						CDrawingInform lDrawingInform = lAnObject.getDrawingInform();
						if(!lDrawingInform.isVisible()) continue;
						if(lAnObject instanceof CTaxiwayLink) {
							continue;
						}
						
						double ltempDistance = Math.sqrt((lDrawingInform.getCoordinationList().get(0).getXCoordination() - lOriginalCoordination.getXCoordination())*(lDrawingInform.getCoordinationList().get(0).getXCoordination() - lOriginalCoordination.getXCoordination()) +
								(lDrawingInform.getCoordinationList().get(0).getYCoordination() - lOriginalCoordination.getYCoordination())*(lDrawingInform.getCoordinationList().get(0).getYCoordination() - lOriginalCoordination.getYCoordination()));

						if(ltempDistance<lDistance) {
							lTheObject = lAnObject;
							lDistance=ltempDistance;
						}					
					}


					double p1X = lTheObject.getDrawingInform().getCoordinationList().get(0).getXCoordination();
					double p1Y = lTheObject.getDrawingInform().getCoordinationList().get(0).getYCoordination();
					CCoordination p1 = changeCoordinatesInCanvas(p1X, p1Y);
//					System.out.println(lTheObject);
					GraphicsContext gc = SimCanvas.getGraphicsContext2D();
					gc.strokeText(lTheObject.toString(), p1.getXCoordination(), p1.getYCoordination());					
					gc.setFill(Color.THISTLE);			
					double lRadius =  10*CAtsolSimMain.getInstance().getViewPointR();
					gc.fillOval(p1.getXCoordination()-lRadius/2, p1.getYCoordination()-lRadius/2,lRadius, lRadius);
				});
				break;
			case "MOUSE_PRESSED":		
				// Initialize Mouse Position for Wheel Dragging				
				iMousePositionXPrev = ((MouseEvent) aEvent).getSceneX();
				iMousePositionYPrev = ((MouseEvent) aEvent).getSceneY();
				break;
			case "MOUSE_CLICKED":		
				// Initialize Mouse Position for Wheel Dragging
				iMousePositionXPrev = ((MouseEvent) aEvent).getSceneX();
				iMousePositionYPrev = ((MouseEvent) aEvent).getSceneY();
				break;
			case "SCROLL":		 // Zoon In/Out		
	
				if(((ScrollEvent) aEvent).getDeltaY()<0) {
					CAtsolSimMain.getInstance().setViewPointR(CAtsolSimMain.getInstance().getViewPointR()*0.7);
				}else {
					CAtsolSimMain.getInstance().setViewPointR(CAtsolSimMain.getInstance().getViewPointR()/0.7);
				}
				
				drawDrawingObjectList();
				break;
			}
		}
		
	}
	
	@SuppressWarnings("static-access")
	public CAtsolSimGuiControl() {
		this.iInstance = this;
	}
	
	public static CAtsolSimGuiControl getInstance() {
		return iInstance;
	}
	public void addview(CAtsolSimGuiView aGuiview) {
		fGuiview = aGuiview;
	}
	
	public Canvas getSimCanvas() {
		return SimCanvas;
	}
	/*
	================================================================
	
						Listeners Section
	
	================================================================
	 */
	
	

	/*
	================================================================
	
							The Others
	
	================================================================
	 */
}






