// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package elements.facility;

/************************************************************/
/**
 * 
 */
public enum ELocation {
	/**
	 * 
	 */
	AIRSIDE,
	/**
	 * 
	 */
	LANDSIDE,
	/**
	 * 
	 */
	TERMINAL,
	/**
	 * 
	 */
	AIRSPACE,
	/**
	 * 
	 */
	GROUND;
};
